### PR TITLE
update item 8 of task 2

### PR DESCRIPTION
**Pull request by meauses**
removed [0].Sku. because it does not provide the output required for the next commands.

### CODE REVIEW

**Comment by polichtm** [comment]
Would you mind clarifying what specifically is the issue with the output of the command you want to replace?
rgds
Marcin

**Comment by meauses** [comment]
The command with Get-AzResources does not provide any data. So when executed the variable stays empty and the whole deployment process of the VM does not work (at least in my case in the Azure Cloud Shell). So when replaced with the new command (it eventually took me three times to find the actual working one...) you can continue with the deployment.

**Comment by polichtm** [comment]
Here is what I'm seeing
image
Can you clarify what specifically is not working for you?
rgds
Marcin

**Comment by meauses** [comment]
Appearantly it did not work because there was no other virtual machine present in the resource group which is a pre-requisite for the variable to be able to be filled. But another student in my AZ100 class had the same issue. I'll check the lab and see if it ensures there should be a vm present in the resource group.

**Comment by polichtm** [comment]
Appreciate the clarification
rgds
Marcin

**Pull request closed without merging**
